### ISSUE TITLE
exception while login

### ISSUE THREAD

**Issue by christopherpross** [miry/online_games_bots#13]
Hey,
I had try out your bot, but, there is an exception while login.
What went wrong here?
I followed the steps in the readme for Macos.

chpross@vmd21292:~$ cd online_games_bots/
chpross@vmd21292:~/online_games_bots$ docker run -e LOG_LEVEL=debug -v $(pwd)/config:/app/config -v $(pwd)/tmp:/app/tmp miry/online_games_bot bundle exec ruby runner.rb
Unable to find image 'miry/online_games_bot:latest' locally
latest: Pulling from miry/online_games_bot
7ddbc47eeb70: Already exists
c1bbdc448b72: Already exists
8c3b70e39044: Already exists
45d437916d57: Already exists
29c0b8a44c93: Pulling fs layer
c9aa98866ffb: Pull complete
6584a4b691b2: Pull complete
842fb67ea81b: Pull complete
758108596d08: Pull complete
dff828979cf3: Pull complete
18e9721273f4: Pull complete
9e553a64ecfd: Pull complete
9eb2588dfeab: Pull complete
c5e5810e287c: Pull complete
529de0265d85: Pull complete
2e7d7ae8994e: Pull complete
8af760dc5257: Pull complete
bec08b509628: Pull complete
07edf5ce4977: Pull complete
f4e5b8d6a5fe: Pull complete
90d993d6b4cf: Pull complete
8202494dbc5a: Pull complete
9f73d93ff2f0: Pull complete
420118cf2250: Pull complete
0a740003ed31: Pull complete
cc54126851cd: Pull complete
5ab96d2c9ae3: Pull complete
3e4d12a37cca: Pull complete
Digest: sha256:dd621fa7b686596e164cb6833559af8cdfc6fe4b83471d8077e79a5083536a81
Status: Downloaded newer image for miry/online_games_bot:latest
I, [2020-02-14T11:50:27.669912 #1]  INFO -- : Started bot lords_and_kinghts_v3 on miry_de
D, [2020-02-14T11:50:27.670553 #1] DEBUG -- : Building List:
D, [2020-02-14T11:50:27.670591 #1] DEBUG -- : [{:level=>3, :name=>"Ore store"}, {:level=>3, :name=>"Wood store"}, {:level=>3, :name=>"Stone store"}, {:level=>5, :name=>"Lumberjack"}, {:level=>5, :name=>"Quarry"}, {:level=>5, :name=>"Ore mine"}, {:level=>2, :name=>"Library"}, {:level=>6, :name=>"Lumberjack"}, {:level=>6, :name=>"Quarry"}, {:level=>6, :name=>"Ore mine"}, {:level=>7, :name=>"Lumberjack"}, {:level=>7, :name=>"Quarry"}, {:level=>7, :name=>"Ore mine"}, {:level=>6, :name=>"Ore store"}, {:level=>6, :name=>"Wood store"}, {:level=>6, :name=>"Stone store"}, {:level=>8, :name=>"Lumberjack"}, {:level=>8, :name=>"Quarry"}, {:level=>8, :name=>"Ore mine"}, {:level=>9, :name=>"Lumberjack"}, {:level=>9, :name=>"Quarry"}, {:level=>9, :name=>"Ore mine"}, {:level=>7, :name=>"Farm"}, {:level=>7, :name=>"Ore store"}, {:level=>7, :name=>"Wood store"}, {:level=>7, :name=>"Stone store"}, {:level=>10, :name=>"Lumberjack"}, {:level=>10, :name=>"Quarry"}, {:level=>10, :name=>"Ore mine"}, {:level=>3, :name=>"Library"}, {:level=>2, :name=>"Tavern"}, {:level=>8, :name=>"Ore store"}, {:level=>8, :name=>"Wood store"}, {:level=>8, :name=>"Stone store"}, {:level=>12, :name=>"Farm"}, {:level=>11, :name=>"Lumberjack"}, {:level=>11, :name=>"Quarry"}, {:level=>11, :name=>"Ore mine"}, {:level=>12, :name=>"Lumberjack"}, {:level=>12, :name=>"Quarry"}, {:level=>12, :name=>"Ore mine"}, {:level=>13, :name=>"Lumberjack"}, {:level=>13, :name=>"Quarry"}, {:level=>13, :name=>"Ore mine"}, {:level=>14, :name=>"Lumberjack"}, {:level=>14, :name=>"Quarry"}, {:level=>14, :name=>"Ore mine"}, {:level=>9, :name=>"Wood store"}, {:level=>9, :name=>"Stone store"}, {:level=>9, :name=>"Ore store"}, {:level=>4, :name=>"Library"}, {:level=>15, :name=>"Lumberjack"}, {:level=>15, :name=>"Quarry"}, {:level=>15, :name=>"Ore mine"}, {:level=>12, :name=>"Wood store"}, {:level=>12, :name=>"Stone store"}, {:level=>12, :name=>"Ore store"}, {:level=>16, :name=>"Lumberjack"}, {:level=>16, :name=>"Quarry"}, {:level=>16, :name=>"Ore mine"}, {:level=>17, :name=>"Lumberjack"}, {:level=>17, :name=>"Quarry"}, {:level=>17, :name=>"Ore mine"}, {:level=>18, :name=>"Lumberjack"}, {:level=>18, :name=>"Quarry"}, {:level=>18, :name=>"Ore mine"}, {:level=>19, :name=>"Lumberjack"}, {:level=>19, :name=>"Quarry"}, {:level=>19, :name=>"Ore mine"}, {:level=>20, :name=>"Lumberjack"}, {:level=>20, :name=>"Quarry"}, {:level=>20, :name=>"Ore mine"}, {:level=>5, :name=>"Keep"}, {:level=>21, :name=>"Lumberjack"}, {:level=>21, :name=>"Quarry"}, {:level=>21, :name=>"Ore mine"}, {:level=>6, :name=>"Keep"}, {:level=>15, :name=>"Wood store"}, {:level=>15, :name=>"Stone store"}, {:level=>15, :name=>"Ore store"}, {:level=>22, :name=>"Lumberjack"}, {:level=>22, :name=>"Quarry"}, {:level=>22, :name=>"Ore mine"}, {:level=>8, :name=>"Keep"}, {:level=>5, :name=>"Market"}, {:level=>17, :name=>"Wood store"}, {:level=>17, :name=>"Stone store"}, {:level=>17, :name=>"Ore store"}, {:level=>9, :name=>"Keep"}, {:level=>nil, :name=>"Wood store"}, {:level=>nil, :name=>"Stone store"}, {:level=>nil, :name=>"Ore store"}, {:level=>nil, :name=>"Keep"}, {:level=>12, :name=>"Farm"}, {:level=>6, :name=>"Library"}, {:level=>5, :name=>"Fortifications"}, {:level=>4, :name=>"Tavern"}, {:level=>8, :name=>"Library"}, {:level=>nil, :name=>"Lumberjack"}, {:level=>nil, :name=>"Quarry"}, {:level=>nil, :name=>"Ore mine"}, {:level=>nil, :name=>"Library"}, {:level=>nil, :name=>"Farm"}, {:level=>nil, :name=>"Arsenal"}, {:level=>nil, :name=>"Fortifications"}, {:level=>nil, :name=>"Wood Storage"}, {:level=>nil, :name=>"Stone Storage"}, {:level=>nil, :name=>"Ore Storage"}, {:level=>nil, :name=>"Townhall"}, {:level=>nil, :name=>"Barracks"}, {:level=>nil, :name=>"University"}, {:level=>nil, :name=>"Fortress Wall"}, {:level=>nil, :name=>"Marketplace"}, {:level=>nil, :name=>"Military camp"}, {:level=>1, :name=>"Tavern Quarter"}]
D, [2020-02-14T11:50:34.813608 #1] DEBUG -- : Fill login information: christopher.pross@icloud.com
D, [2020-02-14T11:52:20.030050 #1] DEBUG -- : FAILED: Bot::LordsAndKnightsV3
D, [2020-02-14T11:52:20.048348 #1] DEBUG -- : screenshot path: "tmp/screenshot_2020-02-14-11-52-20.030.png"
D, [2020-02-14T11:52:20.317996 #1] DEBUG -- : --- Exception
D, [2020-02-14T11:52:20.318072 #1] DEBUG -- : Capybara::ElementNotFound
D, [2020-02-14T11:52:20.318102 #1] DEBUG -- : Unable to find css "form.form--login"
D, [2020-02-14T11:52:20.318136 #1] DEBUG -- : /usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:302:in `block in synced_resolve'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/base.rb:83:in `synchronize'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:291:in `synced_resolve'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:52:in `find'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/session.rb:753:in `find'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/session.rb:342:in `within'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/dsl.rb:53:in `call'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/dsl.rb:53:in `within'
/app/bot/lords_and_knights_v3.rb:22:in `login'
/app/bot/base.rb:55:in `run'
runner.rb:110:in `block in <main>'
runner.rb:85:in `each'
runner.rb:85:in `<main>'
D, [2020-02-14T11:52:20.318157 #1] DEBUG -- : ---- Console
D, [2020-02-14T11:52:20.318248 #1] DEBUG -- : ---- Body
D, [2020-02-14T11:52:20.318262 #1] DEBUG -- : -----
chpross@vmd21292:~/online_games_bots$ ~~~~**

**Comment by miry** [comment]
@christopherpross You should check the folder `tmp`. It suppose to have screenshots file: tmp/screenshot_2020-02-14-11-52-20.030.png

Can you send me to email miry.sof@gmail.com or contact:
 via discord channel: https://discord.gg/VaEtdbC
 gitter: https://gitter.im/Lords-and-Knights-Bot/community

**Comment by miry** [comment]
@christopherpross I have update the code with new fixes. Can you check?

update the
```shell
docker pull miry/online_games_bot:latest
````

and run bot:

```shell
docker run -e LOG_LEVEL=debug -v $(pwd)/config:/app/config -v $(pwd)/tmp:/app/tmp miry/online_games_bot bundle exec ruby runner.rb
```

**Comment by christopherpross** [comment]
Well, that fixed this!
thank you!
