### ISSUE TITLE
capybara session.rb deprecated!

### ISSUE THREAD

**Issue by Hakikat41** [miry/online_games_bots#20]
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/session.rb:753: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:38: warning: The called method `has_selector?' is defined here
I, [2020-06-18T18:51:49.114432 #7]  INFO -- : Choose the server: Helvetica 5 (empfohlen)
I, [2020-06-18T18:52:04.513449 #7]  INFO -- : > Selected castle: XXXX
I, [2020-06-18T18:52:04.513563 #7]  INFO -- : >> Building
I, [2020-06-18T18:52:09.860686 #7]  INFO -- :   >> Nothing todo. Workers are busy.
I, [2020-06-18T18:52:09.860758 #7]  INFO -- : >> Sending troops to missions
I, [2020-06-18T18:52:30.502543 #7]  INFO -- : >> Events
Exited
please help with the warnings, how are the castles selected, I had several castles, it selected the second castle. And where can I define the environment variable for $SERVERS_JSON. It is not good to put the command in bash. Thanks for your help.

**Comment by Hakikat41** [comment]
close

**Comment by miry** [comment]
@Hakikat41 sorry for long response. How did you solve the problem? If you have something that we can learn from your experience to solve your problem?
