### ISSUE TITLE
Bot doesn't work on server: Germanien V (DE) - empfohlen

### ISSUE THREAD

**Issue by Hakikat41** [miry/online_games_bots#24]
Hi miry,

the bot doesn't work on server: Germanien V (DE) - empfohlen, but on other servers it works.
Can you please help?

**Comment by Hakikat41** [comment]
`bundle exec ruby runner.rb -c config/servers.yml
I, [2020-12-29T00:57:40.669564 #42329]  INFO -- : Started bot lords_and_kinghts_v3 on miry_de
WARN: Screenshot could not be saved. `page.current_path` raised exception: #<Capybara::DriverNotFoundError: no driver called :"-c" was found, available drivers: :rack_test, :selenium, :selenium_headless, :selenium_chrome, :selenium_chrome_headless, :chrome_headless>.`

**Comment by miry** [comment]
@Hakikat41 can you provide your config. It seems the config is not YAML correct because of some characters.
